spring:
  datasource:
    #url: jdbc:mysql://192.168.12.149:3306/SOCKS
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.12.201:3306/employees
    username: root
    password: kd!253


api.prefix: spring-test